#!/bin/sh

COMMIT_MSG_FILE=$1
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

if [ "$BRANCH_NAME" = "HEAD" ]; then
  exit 0
fi

if grep -q "^\[$BRANCH_NAME\]" "$COMMIT_MSG_FILE"; then
  exit 0
fi

FIRST_LINE=$(head -n 1 "$COMMIT_MSG_FILE")
REST=$(tail -n +2 "$COMMIT_MSG_FILE")

{
  printf '[%s] %s\n' "$BRANCH_NAME" "$FIRST_LINE"
  printf '%s\n' "$REST"
} > "$COMMIT_MSG_FILE.tmp"

mv "$COMMIT_MSG_FILE.tmp" "$COMMIT_MSG_FILE"