from typing import Protocol
from uuid import UUID

from shared.user.application.dto.user import CreateUserDTO, UserDTO


class IUserRepo(Protocol):
    async def get_user_by_email(self, email: str) -> UserDTO: ...
    async def check_user_email_exists(self, email: str) -> bool: ...
    async def create_user(self, user: CreateUserDTO) -> UUID: ...
    async def get_user_by_id(self, user_id: int) -> UserDTO: ...
    async def get_maybe_user_by_id(self, user_id: int) -> UserDTO | None: ...
